apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.HardwareResource}}-{{.GroupName.DriverContainer}}
  name: {{.HardwareResource}}-{{.GroupName.DriverContainer}}
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{.HardwareResource}}-{{.GroupName.DriverBuild}} 
  name: {{.HardwareResource}}-{{.GroupName.DriverBuild}}
  annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/driver-container-vendor: {{.NodeFeature}}    
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    {{.NodeFeature}}: "true"
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    git:
      ref: master
      uri: https://gitlab.com/nvidia/driver.git
    contextDir: {{.OperatingSystem}}
    type: Git
  strategy:
    dockerStrategy:
      buildArgs:
        - name: "DRIVER_VERSION"
          value: "440.33.01"
  output:
    to:
      kind: ImageStreamTag
      name: {{.HardwareResource}}-{{.GroupName.DriverContainer}}:v{{.KernelVersion}}
