apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
subjects:
- kind: ServiceAccount
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
userNames:
- system:serviceaccount:{{.OperatorNamespace}}:{{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}-entrypoint
data:
  entrypoint.sh: |-
    #!/bin/bash

    chcon -t container_file_t /run/nvidia/driver/dev/*

    /work/run.sh /run/nvidia 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}-init-entrypoint
data:
  entrypoint.sh: |-
    #!/bin/bash
    lsmod | grep nvidia
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
  name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
  annotations:
    specialresource.openshift.io/state: "runtime-enablement"
    specialresource.openshift.io/wait: "true"
spec:
  selector:
    matchLabels:
      app: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{.StateName.DriverContainer}}-{{.HardwareResource}}
                operator: In 
                values:
                - ready 
      initContainers: 
      - image: quay.io/openshift-psap/ubi8-kmod
        name: specialresource-driver-validation-{{.HardwareResource}}
        command: ["/bin/entrypoint.sh"]
        volumeMounts:
        - name: init-entrypoint
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh

      containers:
      - image: nvidia/container-toolkit:1.0.0-alpha.3
        command: ["/bin/entrypoint.sh"]
        env:
        - name: TOOLKIT_ARGS
          value: --symlink /usr/local/nvidia
        - name: RUNTIME_ARGS
        - name: RUNTIME
          value: crio
        imagePullPolicy: IfNotPresent
        name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}-ctr
        resources: {}
        securityContext:
          privileged: true
          seLinuxOptions:
            level: s0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: entrypoint
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /run/nvidia
          mountPropagation: Bidirectional
          name: nvidia-install-path
        - mountPath: /etc/docker
          name: docker-config
        - mountPath: /usr/local/nvidia
          name: nvidia-local
        - mountPath: /usr/share/containers/oci/hooks.d
          name: crio-hooks
      hostPID: true
      nodeSelector:
        {{.NodeFeature}}: "true"
      restartPolicy: Always
      securityContext: {}
      serviceAccount: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
      serviceAccountName: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
      - name: entrypoint
        configMap:
          defaultMode: 0700
          name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}-entrypoint
      - name: init-entrypoint
        configMap:
          defaultMode: 0700
          name: {{.HardwareResource}}-{{.GroupName.RuntimeEnablement}}-init-entrypoint
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
      - hostPath:
          path: /run/nvidia
          type: ""
        name: nvidia-install-path
      - hostPath:
          path: /etc/docker
          type: ""
        name: docker-config
      - hostPath:
          path: /usr/local/nvidia
          type: ""
        name: nvidia-local
      - hostPath:
          path: /etc/containers/oci/hooks.d
          type: ""
        name: crio-hooks
