apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: special-resource-operator
  namespace: REPLACE_NAMESPACE
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "services/finalizers", "endpoints", "persistentvolumeclaims", "events", "configmaps", "configmaplists", "secrets", "serviceaccounts", "nodes"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ['*']
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ['*']
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "create", "watch", "update"]
- apiGroups: ["sro.openshift.io"]
  resources: ['*']
  verbs: ['*']
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: ["build.openshift.io"]
  resources: ["buildconfigs"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- apiGroups: ["build.openshift.io"]
  resources: ["builds"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: special-resource-operator
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints", "securitycontextconstraints/finalizers"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ['*']
- apiGroups: ["sro.openshift.io"]
  resources: ['*']
  verbs: ['*']
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "services/finalizers", "endpoints", "persistentvolumeclaims", "events", "configmaps", "configmaplists", "secrets", "serviceaccounts", "nodes"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ['*']
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ['*']
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "create", "watch", "update"]
- apiGroups: ["sro.openshift.io"]
  resources: ['*']
  verbs: ['*']
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: ["build.openshift.io"]
  resources: ["buildconfigs"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- apiGroups: ["build.openshift.io"]
  resources: ["builds"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]