#Service account for fencing pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.specialresource.metadata.name}}-fencing
  namespace: {{.Values.specialresource.spec.namespace}}

---

#Certificate for fencing pod
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.specialresource.metadata.name}}-vxfen-cert
  namespace: {{.Values.specialresource.spec.namespace}}
  annotations:
     specialresource.openshift.io/wait: "true"
spec:
  commonName: {{.Values.specialresource.metadata.name}}-vxfen
  secretName: vxfen-tls-cert
  duration: 8760h # 365d
  renewBefore: 720h # 30d
  issuerRef:
    name: infoscale-cert-issuer
    kind: Issuer

---
