apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: fpga-xrt-driver
spec:
  chart:
    name: fpga-xrt-driver
    repository:
      name: example
      url: cm://fpga-xrt-driver/fpga-xrt-driver-chart
    version: 4.7.11
  namespace: fpga-xrt-driver
  nodeSelector:
    feature.node.kubernetes.io/pci-1d0f.present: "true"
    node.kubernetes.io/instance-type: f1.2xlarge

  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1

  driverContainer:
    source:
      git:
        uri: "https://github.com/openshift-psap/kvc-xilinx-xrt.git"
        ref: "main"

