name: test

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  ok-to-test:
    name: ok-to-test
    runs-on: ubuntu-20.04
    if: contains(toJSON(github.event.pull_request.labels), '"ok-to-test",')
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
  repo-test:
    name: main-repo
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.head.repo.full_name, 'openshift-psap/special-resource-operator')
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
