name: verify

on: 
  push:
    paths-ignore:
      - "**/README.md"


jobs: 
  verify:
    name: fmt-vet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: add go path
      run: echo '~/go/bin' >> "$GITHUB_PATH"

    - name: make verify
      run: make verify

